# Generated by Django 3.2.7 on 2021-10-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10000)),
                ('book_desc', models.TextField(max_length=10000000000)),
            ],
        ),
    ]
