# Generated by Django 3.2.7 on 2021-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='imgall',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
