# Generated by Django 3.2.7 on 2021-10-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_books_imgall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='imgall',
        ),
    ]
