# Generated by Django 3.2.7 on 2021-10-08 16:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_audio_story_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
