# Generated by Django 3.2.7 on 2021-10-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_alter_books_book_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='book_title',
        ),
    ]
